-- MySQL Script generated by MySQL Workbench
-- Sun Dec  3 02:09:25 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema id1212
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `id1212` ;

-- -----------------------------------------------------
-- Schema id1212
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `id1212` DEFAULT CHARACTER SET utf8 ;
USE `id1212` ;

-- -----------------------------------------------------
-- Table `id1212`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `id1212`.`user` ;

CREATE TABLE IF NOT EXISTS `id1212`.`user` (
  `name` VARCHAR(45) NOT NULL,
  `password` VARCHAR(45) NULL,
  PRIMARY KEY (`name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `id1212`.`file`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `id1212`.`file` ;

CREATE TABLE IF NOT EXISTS `id1212`.`file` (
  `name` VARCHAR(45) NOT NULL,
  `size` BIGINT(20) NULL,
  `public` TINYINT(1) NULL,
  `read` TINYINT(1) NULL,
  `write` TINYINT(1) NULL,
  `owner` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`name`),
  CONSTRAINT `fk_file_user`
    FOREIGN KEY (`owner`)
    REFERENCES `id1212`.`user` (`name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;

CREATE INDEX `fk_file_user_idx` ON `id1212`.`file` (`owner` ASC);

SET SQL_MODE = '';
GRANT USAGE ON *.* TO id1212@localhost;
 DROP USER id1212@localhost;
SET SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';
CREATE USER 'id1212'@'localhost' IDENTIFIED BY 'id1212';

GRANT ALL ON `id1212`.* TO 'id1212'@'localhost';

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

-- -----------------------------------------------------
-- Data for table `id1212`.`user`
-- -----------------------------------------------------
START TRANSACTION;
USE `id1212`;
INSERT INTO `id1212`.`user` (`name`, `password`) VALUES ('test', 'test');
INSERT INTO `id1212`.`user` (`name`, `password`) VALUES ('test2', 'test2');

COMMIT;


-- -----------------------------------------------------
-- Data for table `id1212`.`file`
-- -----------------------------------------------------
START TRANSACTION;
USE `id1212`;
INSERT INTO `id1212`.`file` (`name`, `size`, `public`, `read`, `write`, `owner`) VALUES ('publicRead.txt', 200, 1, 1, 0, 'test');
INSERT INTO `id1212`.`file` (`name`, `size`, `public`, `read`, `write`, `owner`) VALUES ('publicWrite.txt', 100, 1, 1, 1, 'test');
INSERT INTO `id1212`.`file` (`name`, `size`, `public`, `read`, `write`, `owner`) VALUES ('privateTest.txt', 100, 0, 0, 0, 'test');
INSERT INTO `id1212`.`file` (`name`, `size`, `public`, `read`, `write`, `owner`) VALUES ('privateTest2.txt', 100, 0, 0, 0, 'test2');

COMMIT;

